/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/lib/ky/base`; params?: Router.UnknownInputParams; } | { pathname: `/lib/ky/hooks`; params?: Router.UnknownInputParams; } | { pathname: `/lib/ky`; params?: Router.UnknownInputParams; } | { pathname: `/lib/ky/openai`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/custom-hooks`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/query-client`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/query-hooks`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/query-key`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/hooks/app`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/hooks/openai`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/service/app`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/service/openai`; params?: Router.UnknownInputParams; } | { pathname: `/modules/openai/screens/openai-demo`; params?: Router.UnknownInputParams; } | { pathname: `/modules/openai/screens/simple-example`; params?: Router.UnknownInputParams; } | { pathname: `/modules/roles/screens/role-list`; params?: Router.UnknownInputParams; } | { pathname: `/themes/Box`; params?: Router.UnknownInputParams; } | { pathname: `/themes/Text`; params?: Router.UnknownInputParams; } | { pathname: `/themes/Theme`; params?: Router.UnknownInputParams; } | { pathname: `/themes`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/ky/base`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/ky/hooks`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/ky`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/ky/openai`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/react-query/custom-hooks`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/react-query/query-client`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/react-query/query-hooks`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/react-query/query-key`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/react-query/hooks/app`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/react-query/hooks/openai`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/react-query/service/app`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/react-query/service/openai`; params?: Router.UnknownOutputParams; } | { pathname: `/modules/openai/screens/openai-demo`; params?: Router.UnknownOutputParams; } | { pathname: `/modules/openai/screens/simple-example`; params?: Router.UnknownOutputParams; } | { pathname: `/modules/roles/screens/role-list`; params?: Router.UnknownOutputParams; } | { pathname: `/themes/Box`; params?: Router.UnknownOutputParams; } | { pathname: `/themes/Text`; params?: Router.UnknownOutputParams; } | { pathname: `/themes/Theme`; params?: Router.UnknownOutputParams; } | { pathname: `/themes`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/lib/ky/base${`?${string}` | `#${string}` | ''}` | `/lib/ky/hooks${`?${string}` | `#${string}` | ''}` | `/lib/ky${`?${string}` | `#${string}` | ''}` | `/lib/ky/openai${`?${string}` | `#${string}` | ''}` | `/lib/react-query/custom-hooks${`?${string}` | `#${string}` | ''}` | `/lib/react-query/query-client${`?${string}` | `#${string}` | ''}` | `/lib/react-query/query-hooks${`?${string}` | `#${string}` | ''}` | `/lib/react-query/query-key${`?${string}` | `#${string}` | ''}` | `/lib/react-query/hooks/app${`?${string}` | `#${string}` | ''}` | `/lib/react-query/hooks/openai${`?${string}` | `#${string}` | ''}` | `/lib/react-query/service/app${`?${string}` | `#${string}` | ''}` | `/lib/react-query/service/openai${`?${string}` | `#${string}` | ''}` | `/modules/openai/screens/openai-demo${`?${string}` | `#${string}` | ''}` | `/modules/openai/screens/simple-example${`?${string}` | `#${string}` | ''}` | `/modules/roles/screens/role-list${`?${string}` | `#${string}` | ''}` | `/themes/Box${`?${string}` | `#${string}` | ''}` | `/themes/Text${`?${string}` | `#${string}` | ''}` | `/themes/Theme${`?${string}` | `#${string}` | ''}` | `/themes${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/lib/ky/base`; params?: Router.UnknownInputParams; } | { pathname: `/lib/ky/hooks`; params?: Router.UnknownInputParams; } | { pathname: `/lib/ky`; params?: Router.UnknownInputParams; } | { pathname: `/lib/ky/openai`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/custom-hooks`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/query-client`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/query-hooks`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/query-key`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/hooks/app`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/hooks/openai`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/service/app`; params?: Router.UnknownInputParams; } | { pathname: `/lib/react-query/service/openai`; params?: Router.UnknownInputParams; } | { pathname: `/modules/openai/screens/openai-demo`; params?: Router.UnknownInputParams; } | { pathname: `/modules/openai/screens/simple-example`; params?: Router.UnknownInputParams; } | { pathname: `/modules/roles/screens/role-list`; params?: Router.UnknownInputParams; } | { pathname: `/themes/Box`; params?: Router.UnknownInputParams; } | { pathname: `/themes/Text`; params?: Router.UnknownInputParams; } | { pathname: `/themes/Theme`; params?: Router.UnknownInputParams; } | { pathname: `/themes`; params?: Router.UnknownInputParams; };
    }
  }
}
